resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/sparklemotion/nokogiri/
    branch: master

jobs:
<% %w(2.0 2.1 2.2.5 2.3.1).each do |version| %>
  - name: ruby <%= version %>
    serial: true
    serial_groups: [ "ruby" ]
    plan:
      - get: git-repo
        trigger: true
      - task: tests
        config:
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: <%= version.inspect %>
          platform: linux
          inputs:
            - name: git-repo
          run:
            path: bash
            args: ["-c", "bundle install && rake"]
            dir: git-repo
<% end %>
